name: mind_app
description: "A Flutter application for interactive learning and AR experiences"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  
  cupertino_icons: ^1.0.2

  # UI & Theming
  google_fonts: ^6.2.1 # ← used for Lexend (no need to bundle .ttf files)
  flutter_svg: ^2.0.10+1

  # State management (choose one – provider is simpler to start with)
  provider: ^6.1.2
  # riverpod: ^2.5.1
  # flutter_riverpod: ^2.5.1

  # Networking & Storage
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.0
  image_pickers: ^2.0.6

  ##text file need 
  #image_picker: ^0.8.7+5
  google_mlkit_text_recognition: ^0.7.0
  #path_provider: ^2.0.14
  pdf: ^3.10.0
  open_file: ^3.2.1
  file_picker: ^8.0.0
  file_selector: ^0.9.0
  share_plus: ^8.0.1
  #ntl: ^0.18.1

  # Images & Media
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.19.0
  material_symbols_icons: ^4.2781.2
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/images/mindie.png
    - assets/images/category_biology_heart.png
    - assets/images/category_history_ruins.png
    - assets/images/category_engineering_gears.png